parameters:
  hh.quizbundle.backend.content-table: tl_quiz_question
  hh.quizbundle.backend.content-ptable: tl_quiz
services:
  hh.quiz-bundle.backend.tl_content:
    class: HeimrichHannot\QuizBundle\Backend\TlContent
    arguments:
        - ['%hh.quizbundle.backend.content-table%', '%hh.quizbundle.backend.content-ptable%']
  huh.quiz.choice.template:
      class: HeimrichHannot\QuizBundle\Choice\TemplateChoice
      arguments:
        - "@contao.framework"
  huh.quiz.manager:
      class: HeimrichHannot\QuizBundle\Manager\QuizManager
      arguments:
          - "@contao.framework"
  huh.quiz.question.manager:
      class: HeimrichHannot\QuizBundle\Manager\QuizQuestionManager
      arguments:
          - "@contao.framework"
  huh.quiz.answer.manager:
      class: HeimrichHannot\QuizBundle\Manager\QuizAnswerManager
      arguments:
          - "@contao.framework"
  huh.quiz.answer.solving.manager:
      class: HeimrichHannot\QuizBundle\Manager\QuizAnswerSolvingManager
      arguments:
          - "@contao.framework"
  huh.quiz.evaluation.manager:
      class: HeimrichHannot\QuizBundle\Manager\QuizEvaluationManager
      arguments:
          - "@contao.framework"